In [14]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns',50)
pd.set_option('display.width',120)

In [15]:
DATA_PATH = "../data/raw/"
INTERIM_PATH = "../data/interim/"

calendar_df = pd.read_csv(DATA_PATH + "calendar.csv")
sales_val_df = pd.read_csv(DATA_PATH + "sales_train_validation.csv")

In [16]:
sales_val_df.columns

Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1', 'd_2', 'd_3', 'd_4',
       ...
       'd_1904', 'd_1905', 'd_1906', 'd_1907', 'd_1908', 'd_1909', 'd_1910', 'd_1911', 'd_1912', 'd_1913'],
      dtype='object', length=1919)

In [17]:
id_columns = ['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id']

day_columns = [col for col in sales_val_df.columns if col.startswith('d_')]

print('Day columns:',len(day_columns))

Day columns: 1913

In [18]:
sales_long_df = sales_val_df.melt(
    id_vars=id_columns,
    value_vars=day_columns,
    var_name="d",
    value_name="sales"
)

sales_long_df.head()

                              id        item_id    dept_id   cat_id store_id state_id    d  sales
0  HOBBIES_1_001_CA_1_validation  HOBBIES_1_001  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
1  HOBBIES_1_002_CA_1_validation  HOBBIES_1_002  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
2  HOBBIES_1_003_CA_1_validation  HOBBIES_1_003  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
3  HOBBIES_1_004_CA_1_validation  HOBBIES_1_004  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
4  HOBBIES_1_005_CA_1_validation  HOBBIES_1_005  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0

In [19]:
calendar_df.columns

Index(['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd', 'event_name_1', 'event_type_1', 'event_name_2',
       'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI'],
      dtype='object')

In [20]:
calendar_small_df = calendar_df[calendar_df.columns]

In [21]:
sales_long_df = sales_long_df.merge(
    calendar_small_df,
    on="d",
    how="left"
)

In [22]:
sales_long_df.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,weekday,wday,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0

In [24]:
sales_long_df["date"] = pd.to_datetime(sales_long_df["date"])

In [26]:
sales_long_df["sales"].isna().sum()

np.int64(0)

In [27]:
sales_long_df.isna().sum().sort_values(ascending=False).head(10)

event_type_2    58205410
event_name_2    58205410
event_name_1    53631910
event_type_1    53631910
id                     0
store_id               0
cat_id                 0
dept_id                0
item_id                0
state_id               0
dtype: int64

Note:
Global sorting of the full dataset was avoided at this stage due to memory constraints.
Sorting is performed later at the item–store level during feature engineering.

In [32]:
sales_long_df.to_csv(
    "../data/interim/sales_long.csv",
    index=False
)